name = "html_lustre_converter"
version = "1.3.0"
description = "Convert regular HTML markup into Lustre syntax"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "html-lustre-converter" }
links = [{ title = "Lustre", href = "https://lustre.build" }]

target = "javascript"

[javascript]
runtime = "deno"

[javascript.deno]
allow_read = ["test", "gleam.toml"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
javascript_dom_parser = ">= 1.0.0 and < 2.0.0"
glam = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
